spring:
  application:
    name: point-of-sale
  datasource:
    url: jdbc:mysql://localhost:3306/db_pos
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
        
server:
  port: 8082

#Warning
#spring.jpa.properties.jakarta.persistence.sharedCache.mode=ALL

springdoc:
  swagger-ui:
    path: /swagger-ui.html
